Update patch set 5
Patch Set 5:

It was failed with OpenJDk8 due to the java doc @options @packages. I add the <maven.javadoc.failOnError> property in /test-app/test-app-bl-impl/pom.xml as a work around to fix the javadoc for the test-app-bl-impl module. 
However the original fix of this check in is for the issue below in which I think it is missing dependecies. I have add the missing dependecies in /features/pom.xml. If you see any problem with the /features/pom.xml let me know.


java.lang.IllegalStateException: Can't install feature odl-persistence-all/1.0.1-Lithium-SR1:         
Error resolving artifact org.opendaylight.persistence:persistence-jpa:xml:config:1.0.1-Lithium-SR1: Could not find artifact org.opendaylight.persistence:persistence-jpa:xml:config:1.0.1-Lithium-SR1 in defaultlocal (file:/tmp/r/)

https://jenkins.opendaylight.org/releng/view/autorelease/job/autorelease-release-lithium/40/org.opendaylight.persistence$features-persistence/consoleText


Note: Please do not merge this unless George gives a confirm ok to merge.

Patch-set: 5